#if os(Windows)
import Foundation
import CodexBarCore

/// Captured collection inputs. Environment/cookie values may contain secrets and must not be logged.
struct WindowsSpendSnapshotLoader {
    struct Source: Sendable, Equatable {
        let id: String
        let provider: UsageProvider
        let displayName: String
        let modelProviderName: String
        let environment: [String: String]
        let cacheRoot: URL?
        let codexHomePath: String?
        let cursorCookieHeader: String?
        let subscriptionName: WindowsShareStatsSubscriptionName?
        let allowVertexClaudeFallback: Bool
        let includePiSessions: Bool
        var expectedCursorAccountID: String? = nil
        var verifyCodexOwner = false
        var expectedCodexAuthFingerprint: String? = nil
        /// Ownership proof captured at resolve time. A changed Claude profile or Vertex credential
        /// must fail the source instead of retaining another account's prior display value.
        var expectedClaudeSessionScope: String? = nil
        var expectedVertexCredentialFingerprint: String? = nil
        /// Supplied only by the runtime's ownership-confirmed widget context; never generated by the loader.
        var widgetAccountRevision: UUID? = nil
        var expectedWidgetScopeFingerprint: String? = nil

        /// Reuse requires identical captured Source values as well as this ownership policy.
        var supportsRetainedCollection: Bool {
            switch self.provider {
            case .codex: self.verifyCodexOwner && self.expectedCodexAuthFingerprint != nil
            case .cursor: CookieHeaderNormalizer.normalize(self.cursorCookieHeader) != nil
            case .claude: self.expectedClaudeSessionScope != nil
            case .vertexai: self.expectedVertexCredentialFingerprint != nil
            default: false
            }
        }
    }
    enum Failure: Error { case invalidSources, missingCodexHome, codexOwnerChanged, claudeOwnerChanged, vertexOwnerChanged }

    struct Collection {
        let load: WindowsSpendDashboardController.Loader
        let resume: WindowsSpendDashboardController.ContinuationLoader
    }

    static func collection(sources: [Source], settings: WindowsSpendSettings, forceRefresh: Bool = false,
                           allowPricingRefresh: Bool = true,
                           environment: [String: String] = ProcessInfo.processInfo.environment,
                           openCodexCacheRoot: URL? = nil) -> Collection {
        // Duplicate IDs are rejected by the native loader; grouping avoids a dictionary trap before it runs.
        let providers = Dictionary(grouping: sources, by: \.id).compactMapValues { $0.first?.provider }
        let session = WindowsSpendCollectionSession(sourceProviders: providers, settings: settings,
            nativeLoader: { days, pending, now in
                let selected = pending.map { ids in sources.filter { ids.contains($0.id) } } ?? sources
                return try await Self.make(sources: selected, forceRefresh: forceRefresh,
                    allowPricingRefresh: pending == nil && allowPricingRefresh,
                    calendar: settings.bucketCalendar, capturedAt: now)(days)
            }, supplementLoader: { now, days in
                try WindowsOpenCodexSpendSource.capture(settings: settings, environment: environment,
                    cacheRoot: openCodexCacheRoot ?? OpenCodexUsageLog.cacheRoot(), now: now, historyDays: days)
            })
        return Collection(load: { days in try await session.begin(days: days) },
                          resume: { days, ids in try await session.resume(days: days, sourceIDs: ids) })
    }

    static func make(sources: [Source], settings: WindowsSpendSettings, forceRefresh: Bool = false,
                     allowPricingRefresh: Bool = true,
                     environment: [String: String] = ProcessInfo.processInfo.environment,
                     openCodexCacheRoot: URL? = nil) -> WindowsSpendDashboardController.Loader {
        let native = self.make(sources: sources, forceRefresh: forceRefresh, allowPricingRefresh: allowPricingRefresh,
                               calendar: settings.bucketCalendar)
        return { days in
            let scan = try await native(days)
            let merged = try WindowsOpenCodexSpendSource.merge(inputs: scan.inputs, settings: settings,
                environment: environment, cacheRoot: openCodexCacheRoot ?? OpenCodexUsageLog.cacheRoot(),
                now: scan.capturedAt, historyDays: max(1, min(WindowsSpendHistoryPolicy.scanDays, days)))
            return .init(inputs: merged.inputs, subscriptionNames: scan.subscriptionNames,
                         sourceFailures: scan.sourceFailures, openCodexObservation: merged.observation, capturedAt: scan.capturedAt,
                         widgetCosts: scan.widgetCosts, widgetCostFailures: scan.widgetCostFailures,
                         retentionEligibleSourceIDs: scan.retentionEligibleSourceIDs)
        }
    }

    static func make(sources: [Source], forceRefresh: Bool = false,
                     allowPricingRefresh: Bool = true, calendar: Calendar = .current,
                     capturedAt: Date? = nil) -> WindowsSpendDashboardController.Loader {
        { days in
            guard Set(sources.map(\.id)).count == sources.count,
                  sources.allSatisfy({ !$0.id.isEmpty }) else { throw Failure.invalidSources }
            let now = capturedAt ?? Date()
            let historyDays = max(1, min(WindowsSpendHistoryPolicy.scanDays, days))
            var inputs: [WindowsSpendDashboardModel.ProviderInput] = []
            var names: [String: WindowsShareStatsSubscriptionName] = [:]
            var failures: [WindowsSpendDashboardController.SourceFailure] = []
            var widgetCosts: [WindowsWidgetSnapshotBuilder.CostOnlyObservation] = []
            var widgetFailures: [WindowsSpendDashboardController.SourceFailure] = []
            // Sequential collection avoids overlapping local scans and required/optional child lifetimes.
            for source in sources {
                try Task.checkCancellation()
                do {
                    let environment: [String: String]
                    if source.provider == .codex {
                        guard let home = source.codexHomePath,
                              let normalized = CodexHomeScope.normalizedHomePath(home) else { throw Failure.missingCodexHome }
                        environment = CodexHomeScope.scopedEnvironment(base: source.environment, codexHome: normalized)
                    } else {
                        environment = source.environment
                    }
                    var cacheRoot = source.cacheRoot
                    let capturedFingerprint: String?
                    if source.provider == .codex, source.verifyCodexOwner {
                        guard let home = source.codexHomePath else { throw Failure.missingCodexHome }
                        var directory: ObjCBool = false
                        guard FileManager.default.fileExists(atPath: home, isDirectory: &directory), directory.boolValue,
                              FileManager.default.isReadableFile(atPath: home) else { throw Failure.missingCodexHome }
                        capturedFingerprint = try CodexAuthFingerprint.fingerprintIfPresent(homePath: home)
                        if let expected = source.expectedCodexAuthFingerprint, capturedFingerprint != expected {
                            throw Failure.codexOwnerChanged
                        }
                        // A rotated auth file cannot write into the previously captured owner's cache scope.
                        cacheRoot = cacheRoot?.appendingPathComponent(capturedFingerprint ?? "missing-auth", isDirectory: true)
                    } else { capturedFingerprint = nil }
                    // Claude/Vertex local scans have no remote account echo, so the captured local
                    // ownership proof is re-checked before and after the fetch. A changed profile or
                    // credential fails the source rather than letting prior data look current.
                    if source.provider == .claude, let expected = source.expectedClaudeSessionScope {
                        guard ClaudeAccountProfile.identifiedSessionScope(environment: environment) == expected
                        else { throw Failure.claudeOwnerChanged }
                    }
                    if source.provider == .vertexai, let expected = source.expectedVertexCredentialFingerprint {
                        guard VertexAIOAuthCredentialsStore.credentialFileFingerprint(environment: environment) == expected
                        else { throw Failure.vertexOwnerChanged }
                    }
                    let fetcher = CostUsageFetcher(cacheRoot: cacheRoot, calendar: calendar)
                    let snapshot = try await fetcher.loadTokenSnapshot(provider: source.provider,
                        environment: environment, now: now, forceRefresh: forceRefresh,
                        allowVertexClaudeFallback: source.allowVertexClaudeFallback,
                        codexHomePath: source.codexHomePath, historyDays: historyDays,
                        cursorCookieHeaderOverride: source.cursorCookieHeader,
                        cursorExpectedAccountID: source.expectedCursorAccountID,
                        allowPricingRefresh: allowPricingRefresh, refreshPricingInBackground: false,
                        includePiSessions: source.includePiSessions)
                    try Task.checkCancellation()
                    let activity: CostUsageTokenActivityCache?
                    if source.provider == .codex {
                        activity = await fetcher.loadCachedCodexTokenActivity(now: now,
                            codexHomePath: source.codexHomePath, maximumDays: historyDays)
                    } else {
                        activity = nil
                    }
                    try Task.checkCancellation()
                    if source.provider == .codex, source.verifyCodexOwner, let home = source.codexHomePath,
                       try CodexAuthFingerprint.fingerprintIfPresent(homePath: home) != capturedFingerprint {
                        throw Failure.codexOwnerChanged
                    }
                    if source.provider == .claude, let expected = source.expectedClaudeSessionScope,
                       ClaudeAccountProfile.identifiedSessionScope(environment: environment) != expected {
                        throw Failure.claudeOwnerChanged
                    }
                    if source.provider == .vertexai, let expected = source.expectedVertexCredentialFingerprint,
                       VertexAIOAuthCredentialsStore.credentialFileFingerprint(environment: environment) != expected {
                        throw Failure.vertexOwnerChanged
                    }
                    inputs.append(.init(id: source.id, provider: source.provider, displayName: source.displayName,
                        modelProviderName: source.modelProviderName, snapshot: snapshot, tokenActivityCache: activity))
                    if let name = source.subscriptionName { names[source.id] = name }
                    if let revision = source.widgetAccountRevision,
                       WindowsWidgetConfiguration.selectableProviders.contains(source.provider) {
                        do {
                            if source.provider == .codex {
                                guard source.verifyCodexOwner, let expected = source.expectedCodexAuthFingerprint,
                                      capturedFingerprint == expected else { throw Failure.codexOwnerChanged }
                            }
                            if source.provider == .cursor {
                                guard let account = source.expectedCursorAccountID, !account.isEmpty else {
                                    throw WindowsWidgetCostAdapter.Failure.scopeChanged
                                }
                            }
                            if source.provider == .claude {
                                guard let expected = source.expectedClaudeSessionScope,
                                      ClaudeAccountProfile.identifiedSessionScope(environment: environment) == expected
                                else { throw Failure.claudeOwnerChanged }
                            }
                            let cost = try WindowsWidgetCostAdapter.make(provider: source.provider, snapshot: snapshot,
                                confirmedAccountRevision: revision, expectedScopeFingerprint: source.expectedWidgetScopeFingerprint, now: now)
                            widgetCosts.append(.init(provider: source.provider, cost: cost))
                        } catch {
                            // The cost UI still has a valid scan; only widget publication failed its stricter boundary.
                            let ownershipFailure: Bool
                            switch error {
                            case WindowsWidgetCostAdapter.Failure.scopeChanged, Failure.codexOwnerChanged: ownershipFailure = true
                            default: ownershipFailure = false
                            }
                            widgetFailures.append(.init(sourceID: source.id, provider: source.provider,
                                accountIdentityUnconfirmed: ownershipFailure))
                        }
                    }
                } catch {
                    // Cancellation aborts the whole generation; an individual source error does not.
                    try Task.checkCancellation()
                    if error is CancellationError { throw error }
                    let inventoryPending: Bool
                    let discoveredFiles: Int?
                    let completedFiles: Int?
                    var verifyingContent = false
                    switch error {
                    case let CostUsageError.localInventoryPending(count):
                        inventoryPending = true
                        discoveredFiles = count
                        completedFiles = nil
                    case let CostUsageError.localContentPending(completed, total):
                        inventoryPending = true
                        discoveredFiles = total
                        completedFiles = completed
                    case let CostUsageError.localContentVerificationPending(total):
                        inventoryPending = true
                        discoveredFiles = total
                        completedFiles = total
                        verifyingContent = true
                    default:
                        inventoryPending = false
                        discoveredFiles = nil
                        completedFiles = nil
                    }
                    let ownerFailure = error as? Failure
                    let identityUnconfirmed = error is CursorCostAccountIdentityError
                        || ownerFailure == .codexOwnerChanged || ownerFailure == .claudeOwnerChanged
                        || ownerFailure == .vertexOwnerChanged
                    failures.append(.init(sourceID: source.id, provider: source.provider,
                        accountIdentityUnconfirmed: identityUnconfirmed,
                        localInventoryPending: inventoryPending, discoveredFiles: discoveredFiles,
                        completedFiles: completedFiles, verifyingContent: verifyingContent))
                }
            }
            return .init(inputs: inputs, subscriptionNames: names, sourceFailures: failures, capturedAt: now,
                         widgetCosts: widgetCosts, widgetCostFailures: widgetFailures,
                         retentionEligibleSourceIDs: Set(sources.filter(\.supportsRetainedCollection).map(\.id)))
        }
    }
}
#endif
