#if os(Windows)
import Foundation
import CodexBarCore

/// Captured collection inputs. Environment/cookie values may contain secrets and must not be logged.
struct WindowsSpendSnapshotLoader {
    struct Source: Sendable, Equatable {
        let id: String
        let provider: UsageProvider
        let displayName: String
        let modelProviderName: String
        let environment: [String: String]
        let cacheRoot: URL?
        let codexHomePath: String?
        let cursorCookieHeader: String?
        let subscriptionName: WindowsShareStatsSubscriptionName?
        let allowVertexClaudeFallback: Bool
        let includePiSessions: Bool
        var expectedCursorAccountID: String? = nil
        var verifyCodexOwner = false
        var expectedCodexAuthFingerprint: String? = nil
        /// Supplied only by the runtime's ownership-confirmed widget context; never generated by the loader.
        var widgetAccountRevision: UUID? = nil
        var expectedWidgetScopeFingerprint: String? = nil

        /// Reuse requires identical captured Source values as well as this ownership policy.
        var supportsRetainedCollection: Bool {
            switch self.provider {
            case .codex: self.verifyCodexOwner && self.expectedCodexAuthFingerprint != nil
            case .cursor: CookieHeaderNormalizer.normalize(self.cursorCookieHeader) != nil
            default: false
            }
        }
    }
    enum Failure: Error { case invalidSources, missingCodexHome, codexOwnerChanged }

    static func make(sources: [Source], settings: WindowsSpendSettings, forceRefresh: Bool = false,
                     allowPricingRefresh: Bool = true,
                     environment: [String: String] = ProcessInfo.processInfo.environment,
                     openCodexCacheRoot: URL? = nil) -> WindowsSpendDashboardController.Loader {
        let native = self.make(sources: sources, forceRefresh: forceRefresh, allowPricingRefresh: allowPricingRefresh,
                               calendar: settings.bucketCalendar)
        return { days in
            let scan = try await native(days)
            let merged = try WindowsOpenCodexSpendSource.merge(inputs: scan.inputs, settings: settings,
                environment: environment, cacheRoot: openCodexCacheRoot ?? OpenCodexUsageLog.cacheRoot(),
                now: scan.capturedAt, historyDays: max(1, min(WindowsSpendHistoryPolicy.scanDays, days)))
            return .init(inputs: merged.inputs, subscriptionNames: scan.subscriptionNames,
                         sourceFailures: scan.sourceFailures, openCodexObservation: merged.observation, capturedAt: scan.capturedAt,
                         widgetCosts: scan.widgetCosts, widgetCostFailures: scan.widgetCostFailures)
        }
    }

    static func make(sources: [Source], forceRefresh: Bool = false,
                     allowPricingRefresh: Bool = true, calendar: Calendar = .current) -> WindowsSpendDashboardController.Loader {
        { days in
            guard Set(sources.map(\.id)).count == sources.count,
                  sources.allSatisfy({ !$0.id.isEmpty }) else { throw Failure.invalidSources }
            let now = Date()
            let historyDays = max(1, min(WindowsSpendHistoryPolicy.scanDays, days))
            var inputs: [WindowsSpendDashboardModel.ProviderInput] = []
            var names: [String: WindowsShareStatsSubscriptionName] = [:]
            var failures: [WindowsSpendDashboardController.SourceFailure] = []
            var widgetCosts: [WindowsWidgetSnapshotBuilder.CostOnlyObservation] = []
            var widgetFailures: [WindowsSpendDashboardController.SourceFailure] = []
            // Sequential collection avoids overlapping local scans and required/optional child lifetimes.
            for source in sources {
                try Task.checkCancellation()
                do {
                    let environment: [String: String]
                    if source.provider == .codex {
                        guard let home = source.codexHomePath,
                              let normalized = CodexHomeScope.normalizedHomePath(home) else { throw Failure.missingCodexHome }
                        environment = CodexHomeScope.scopedEnvironment(base: source.environment, codexHome: normalized)
                    } else {
                        environment = source.environment
                    }
                    var cacheRoot = source.cacheRoot
                    let capturedFingerprint: String?
                    if source.provider == .codex, source.verifyCodexOwner {
                        guard let home = source.codexHomePath else { throw Failure.missingCodexHome }
                        var directory: ObjCBool = false
                        guard FileManager.default.fileExists(atPath: home, isDirectory: &directory), directory.boolValue,
                              FileManager.default.isReadableFile(atPath: home) else { throw Failure.missingCodexHome }
                        capturedFingerprint = try CodexAuthFingerprint.fingerprintIfPresent(homePath: home)
                        if let expected = source.expectedCodexAuthFingerprint, capturedFingerprint != expected {
                            throw Failure.codexOwnerChanged
                        }
                        // A rotated auth file cannot write into the previously captured owner's cache scope.
                        cacheRoot = cacheRoot?.appendingPathComponent(capturedFingerprint ?? "missing-auth", isDirectory: true)
                    } else { capturedFingerprint = nil }
                    let fetcher = CostUsageFetcher(cacheRoot: cacheRoot, calendar: calendar)
                    let snapshot = try await fetcher.loadTokenSnapshot(provider: source.provider,
                        environment: environment, now: now, forceRefresh: forceRefresh,
                        allowVertexClaudeFallback: source.allowVertexClaudeFallback,
                        codexHomePath: source.codexHomePath, historyDays: historyDays,
                        cursorCookieHeaderOverride: source.cursorCookieHeader,
                        cursorExpectedAccountID: source.expectedCursorAccountID,
                        allowPricingRefresh: allowPricingRefresh, refreshPricingInBackground: false,
                        includePiSessions: source.includePiSessions)
                    try Task.checkCancellation()
                    let activity: CostUsageTokenActivityCache?
                    if source.provider == .codex {
                        activity = await fetcher.loadCachedCodexTokenActivity(now: now,
                            codexHomePath: source.codexHomePath, maximumDays: historyDays)
                    } else {
                        activity = nil
                    }
                    try Task.checkCancellation()
                    if source.provider == .codex, source.verifyCodexOwner, let home = source.codexHomePath,
                       try CodexAuthFingerprint.fingerprintIfPresent(homePath: home) != capturedFingerprint {
                        throw Failure.codexOwnerChanged
                    }
                    inputs.append(.init(id: source.id, provider: source.provider, displayName: source.displayName,
                        modelProviderName: source.modelProviderName, snapshot: snapshot, tokenActivityCache: activity))
                    if let name = source.subscriptionName { names[source.id] = name }
                    if let revision = source.widgetAccountRevision,
                       WindowsWidgetConfiguration.selectableProviders.contains(source.provider) {
                        do {
                            if source.provider == .codex {
                                guard source.verifyCodexOwner, let expected = source.expectedCodexAuthFingerprint,
                                      capturedFingerprint == expected else { throw Failure.codexOwnerChanged }
                            }
                            if source.provider == .cursor {
                                guard let account = source.expectedCursorAccountID, !account.isEmpty else {
                                    throw WindowsWidgetCostAdapter.Failure.scopeChanged
                                }
                            }
                            let cost = try WindowsWidgetCostAdapter.make(provider: source.provider, snapshot: snapshot,
                                confirmedAccountRevision: revision, expectedScopeFingerprint: source.expectedWidgetScopeFingerprint, now: now)
                            widgetCosts.append(.init(provider: source.provider, cost: cost))
                        } catch {
                            // The cost UI still has a valid scan; only widget publication failed its stricter boundary.
                            let ownershipFailure: Bool
                            switch error {
                            case WindowsWidgetCostAdapter.Failure.scopeChanged, Failure.codexOwnerChanged: ownershipFailure = true
                            default: ownershipFailure = false
                            }
                            widgetFailures.append(.init(sourceID: source.id, provider: source.provider,
                                accountIdentityUnconfirmed: ownershipFailure))
                        }
                    }
                } catch {
                    // Cancellation aborts the whole generation; an individual source error does not.
                    try Task.checkCancellation()
                    if error is CancellationError { throw error }
                    let inventoryPending: Bool
                    if case CostUsageError.localInventoryPending = error { inventoryPending = true }
                    else { inventoryPending = false }
                    failures.append(.init(sourceID: source.id, provider: source.provider,
                        accountIdentityUnconfirmed: error is CursorCostAccountIdentityError,
                        localInventoryPending: inventoryPending))
                }
            }
            return .init(inputs: inputs, subscriptionNames: names, sourceFailures: failures, capturedAt: now,
                         widgetCosts: widgetCosts, widgetCostFailures: widgetFailures)
        }
    }
}
#endif
