#if os(Windows)
import Foundation

/// Incremental Windows menu catalog copied from the original app's Localizable.strings.
/// Resolved while building menus; language changes require no new status request.
enum WindowsStatusLocalization {
    static var supportedLanguages: [String] { self.catalog.keys.sorted() }

    static func nativeName(for language: String) -> String {
        Locale(identifier: language).localizedString(forIdentifier: language) ?? language
    }

    static func text(_ key: String) -> String {
        let defaults = UserDefaults(suiteName: WindowsRefreshSettings.suiteName) ?? .standard
        let configured = defaults.string(forKey: "appLanguage")?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        let preferences = configured.isEmpty ? Locale.preferredLanguages : [configured]
        let language = Bundle.preferredLocalizations(from: self.catalog.keys.sorted(), forPreferences: preferences).first ?? "en"
        return self.catalog[language]?[key] ?? self.catalog["en"]?[key] ?? key
    }

    private static let catalog: [String: [String: String]] = [
        "ar": [
            "refresh_on_open_title": "التحديث عند فتح القائمة",
            "Refresh": "تحديث",
            "refresh_interval_title": "فاصل التحديث",
            "refresh_manual": "الدليل",
            "refresh_1min": "دقيقة واحدة",
            "refresh_2min": "دقيقتان",
            "refresh_5min": "5 دقائق",
            "refresh_15min": "15 دقيقة",
            "refresh_30min": "30 دقيقة",
            "refresh_adaptive": "تكيفي",
            "Quit": "استقال",
            "language_title": "اللغة",
            "language_system": "النظام",
            "check_provider_status_title": "تحقق من حالة المزود",
            "status_operational": "التشغيل",
            "status_degraded": "أداء متدهور",
            "status_partial_outage": "انقطاع جزئي",
            "status_major_outage": "انقطاع كبير",
            "status_maintenance": "الصيانة",
            "status_unknown": "الحالة غير معروفة",
            "Status Page": "صفحة الحالة",
        ],
        "ca": [
            "refresh_on_open_title": "Actualitza en obrir el menú",
            "Refresh": "Actualitza",
            "refresh_interval_title": "Interval d'actualització",
            "refresh_manual": "Manual",
            "refresh_1min": "1 min",
            "refresh_2min": "2 min",
            "refresh_5min": "5 min",
            "refresh_15min": "15 min",
            "refresh_30min": "30 min",
            "refresh_adaptive": "Adaptatiu",
            "Quit": "Sortiu",
            "language_title": "Idioma",
            "language_system": "Sistema",
            "check_provider_status_title": "Comproveu l'estat del proveïdor",
            "status_operational": "Operatiu",
            "status_degraded": "Rendiment degradat",
            "status_partial_outage": "Interrupció parcial",
            "status_major_outage": "Interrupció greu",
            "status_maintenance": "Manteniment",
            "status_unknown": "Estat desconegut",
            "Status Page": "Pàgina d'estat",
        ],
        "de": [
            "refresh_on_open_title": "Beim Öffnen des Menüs aktualisieren",
            "Refresh": "Aktualisieren",
            "refresh_interval_title": "Aktualisierungsintervall",
            "refresh_manual": "Manuell",
            "refresh_1min": "1 Minute",
            "refresh_2min": "2 Min",
            "refresh_5min": "5 Min",
            "refresh_15min": "15 Min",
            "refresh_30min": "30 Min",
            "refresh_adaptive": "Adaptiv",
            "Quit": "Beenden",
            "language_title": "Sprache",
            "language_system": "System",
            "check_provider_status_title": "Anbieterstatus prüfen",
            "status_operational": "Betriebsbereit",
            "status_degraded": "Eingeschränkte Leistung",
            "status_partial_outage": "Teilweiser Ausfall",
            "status_major_outage": "Schwerwiegender Ausfall",
            "status_maintenance": "Wartung",
            "status_unknown": "Status unbekannt",
            "Status Page": "Statusseite",
        ],
        "en": [
            "refresh_on_open_title": "Refresh when the menu opens",
            "Refresh": "Refresh",
            "refresh_interval_title": "Refresh interval",
            "refresh_manual": "Manual",
            "refresh_1min": "1 min",
            "refresh_2min": "2 min",
            "refresh_5min": "5 min",
            "refresh_15min": "15 min",
            "refresh_30min": "30 min",
            "refresh_adaptive": "Adaptive",
            "Quit": "Quit",
            "language_title": "Language",
            "language_system": "System",
            "check_provider_status_title": "Check provider status",
            "status_operational": "Operational",
            "status_degraded": "Degraded performance",
            "status_partial_outage": "Partial outage",
            "status_major_outage": "Major outage",
            "status_maintenance": "Maintenance",
            "status_unknown": "Status unknown",
            "Status Page": "Status Page",
        ],
        "es": [
            "refresh_on_open_title": "Actualizar al abrir el menú",
            "Refresh": "Actualizar",
            "refresh_interval_title": "Intervalo de actualización",
            "refresh_manual": "Manual",
            "refresh_1min": "1 min",
            "refresh_2min": "2 min",
            "refresh_5min": "5 min",
            "refresh_15min": "15 min",
            "refresh_30min": "30 min",
            "refresh_adaptive": "Adaptativo",
            "Quit": "Salir",
            "language_title": "Idioma",
            "language_system": "Sistema",
            "check_provider_status_title": "Comprobar estado del proveedor",
            "status_operational": "Operativo",
            "status_degraded": "Rendimiento degradado",
            "status_partial_outage": "Interrupción parcial",
            "status_major_outage": "Interrupción grave",
            "status_maintenance": "Mantenimiento",
            "status_unknown": "Estado desconocido",
            "Status Page": "Página de estado",
        ],
        "fa": [
            "refresh_on_open_title": "بازخوانی هنگام باز کردن منو",
            "Refresh": "تازه سازی",
            "refresh_interval_title": "فاصله تازه‌سازی",
            "refresh_manual": "دفترچه راهنما",
            "refresh_1min": "۱ دقیقه",
            "refresh_2min": "۲ دقیقه",
            "refresh_5min": "۵ دقیقه",
            "refresh_15min": "۱۵ دقیقه",
            "refresh_30min": "۳۰ دقیقه",
            "refresh_adaptive": "تطبیقی",
            "Quit": "ترک کن",
            "language_title": "زبان",
            "language_system": "سیستم",
            "check_provider_status_title": "وضعیت ارائه دهنده را بررسی کنید",
            "status_operational": "عملیاتی",
            "status_degraded": "کارایی کاهش‌یافته",
            "status_partial_outage": "قطعی جزئی",
            "status_major_outage": "قطعی عمده",
            "status_maintenance": "نگهداری",
            "status_unknown": "وضعیت نامشخص",
            "Status Page": "صفحه وضعیت",
        ],
        "fr": [
            "refresh_on_open_title": "Actualiser à l'ouverture du menu",
            "Refresh": "Actualiser",
            "refresh_interval_title": "Intervalle d’actualisation",
            "refresh_manual": "Manuel",
            "refresh_1min": "1 minute",
            "refresh_2min": "2 minutes",
            "refresh_5min": "5 minutes",
            "refresh_15min": "15 minutes",
            "refresh_30min": "30 minutes",
            "refresh_adaptive": "Adaptatif",
            "Quit": "Quitter",
            "language_title": "Langue",
            "language_system": "Système",
            "check_provider_status_title": "Vérifier l'état des fournisseurs",
            "status_operational": "Opérationnel",
            "status_degraded": "Performances dégradées",
            "status_partial_outage": "Dégradation partielle",
            "status_major_outage": "Panne majeure",
            "status_maintenance": "Maintenance",
            "status_unknown": "Statut inconnu",
            "Status Page": "Page d'état",
        ],
        "gl": [
            "refresh_on_open_title": "Actualizar ao abrir o menú",
            "Refresh": "Actualizar",
            "refresh_interval_title": "Intervalo de actualización",
            "refresh_manual": "Manual",
            "refresh_1min": "1 min",
            "refresh_2min": "2 min",
            "refresh_5min": "5 min",
            "refresh_15min": "15 min",
            "refresh_30min": "30 min",
            "Quit": "Saír",
            "refresh_adaptive": "Adaptativa",
            "language_title": "Idioma",
            "language_system": "Sistema",
            "check_provider_status_title": "Comprobar o estado do provedor",
            "status_operational": "Operativo",
            "status_degraded": "Rendemento degradado",
            "status_partial_outage": "Interrupción parcial",
            "status_major_outage": "Interrupción grave",
            "status_maintenance": "Mantemento",
            "status_unknown": "Estado descoñecido",
            "Status Page": "Páxina de estado",
        ],
        "id": [
            "refresh_on_open_title": "Segarkan saat menu dibuka",
            "Refresh": "Segarkan",
            "refresh_interval_title": "Interval penyegaran",
            "refresh_manual": "Manual",
            "refresh_1min": "1 mnt",
            "refresh_2min": "2 mnt",
            "refresh_5min": "5 mnt",
            "refresh_15min": "15 mnt",
            "refresh_30min": "30 mnt",
            "refresh_adaptive": "Adaptif",
            "Quit": "Keluar",
            "language_title": "Bahasa",
            "language_system": "Sistem",
            "check_provider_status_title": "Periksa status penyedia",
            "status_operational": "Operasional",
            "status_degraded": "Performa menurun",
            "status_partial_outage": "Gangguan sebagian",
            "status_major_outage": "Gangguan besar",
            "status_maintenance": "Pemeliharaan",
            "status_unknown": "Status tidak diketahui",
            "Status Page": "Halaman Status",
        ],
        "it": [
            "refresh_on_open_title": "Aggiorna all'apertura del menu",
            "Refresh": "Aggiorna",
            "refresh_interval_title": "Intervallo di aggiornamento",
            "refresh_manual": "Manuale",
            "refresh_1min": "1 min.",
            "refresh_2min": "2 min.",
            "refresh_5min": "5 min.",
            "refresh_15min": "15 min.",
            "refresh_30min": "30 min.",
            "refresh_adaptive": "Adattivo",
            "Quit": "Esci",
            "language_title": "Lingua",
            "language_system": "Sistema",
            "check_provider_status_title": "Controlla stato provider",
            "status_operational": "Operativo",
            "status_degraded": "Prestazioni ridotte",
            "status_partial_outage": "Interruzione parziale",
            "status_major_outage": "Interruzione grave",
            "status_maintenance": "Manutenzione",
            "status_unknown": "Stato sconosciuto",
            "Status Page": "Pagina di stato",
        ],
        "ja": [
            "refresh_on_open_title": "メニューを開いたときに更新",
            "Refresh": "更新",
            "refresh_interval_title": "更新間隔",
            "refresh_manual": "手動",
            "refresh_1min": "1分",
            "refresh_2min": "2分",
            "refresh_5min": "5分",
            "refresh_15min": "15分",
            "refresh_30min": "30分",
            "refresh_adaptive": "アダプティブ",
            "Quit": "終了",
            "language_title": "言語",
            "language_system": "システム",
            "check_provider_status_title": "プロバイダのステータスを確認",
            "status_operational": "正常稼働中",
            "status_degraded": "パフォーマンス低下",
            "status_partial_outage": "一部障害",
            "status_major_outage": "重大な障害",
            "status_maintenance": "メンテナンス中",
            "status_unknown": "ステータス不明",
            "Status Page": "ステータスページ",
        ],
        "ko": [
            "refresh_on_open_title": "메뉴를 열 때 새로 고침",
            "Refresh": "새로 고침",
            "refresh_interval_title": "새로 고침 주기",
            "refresh_manual": "수동",
            "refresh_1min": "1분",
            "refresh_2min": "2분",
            "refresh_5min": "5분",
            "refresh_15min": "15분",
            "refresh_30min": "30분",
            "refresh_adaptive": "적응형",
            "Quit": "종료",
            "language_title": "언어",
            "language_system": "시스템",
            "check_provider_status_title": "공급자 상태 확인",
            "status_operational": "정상 작동",
            "status_degraded": "성능 저하",
            "status_partial_outage": "부분 장애",
            "status_major_outage": "주요 장애",
            "status_maintenance": "유지 보수",
            "status_unknown": "상태 알 수 없음",
            "Status Page": "상태 페이지",
        ],
        "nl": [
            "refresh_on_open_title": "Vernieuwen bij openen van menu",
            "Refresh": "Vernieuwen",
            "refresh_interval_title": "Vernieuwingsinterval",
            "refresh_manual": "Handmatig",
            "refresh_1min": "1 min",
            "refresh_2min": "2 minuten",
            "refresh_5min": "5 min",
            "refresh_15min": "15 minuten",
            "refresh_30min": "30 min",
            "refresh_adaptive": "Adaptief",
            "Quit": "Stoppen",
            "language_title": "Taal",
            "language_system": "Systeem",
            "check_provider_status_title": "Controleer de status van de provider",
            "status_operational": "Operationeel",
            "status_degraded": "Verminderde prestaties",
            "status_partial_outage": "Gedeeltelijke uitval",
            "status_major_outage": "Grote storing",
            "status_maintenance": "Onderhoud",
            "status_unknown": "Status onbekend",
            "Status Page": "Statuspagina",
        ],
        "pl": [
            "refresh_on_open_title": "Odśwież po otwarciu menu",
            "Refresh": "Odśwież",
            "refresh_interval_title": "Częstotliwość odświeżania",
            "refresh_manual": "Ręcznie",
            "refresh_1min": "Co 1 min",
            "refresh_2min": "Co 2 min",
            "refresh_5min": "Co 5 min",
            "refresh_15min": "Co 15 min",
            "refresh_30min": "Co 30 min",
            "refresh_adaptive": "Adaptacyjny",
            "Quit": "Zakończ",
            "language_title": "Język",
            "language_system": "System",
            "check_provider_status_title": "Sprawdzaj status dostawców",
            "status_operational": "Operacyjne",
            "status_degraded": "Obniżona wydajność",
            "status_partial_outage": "Częściowa awaria",
            "status_major_outage": "Poważna awaria",
            "status_maintenance": "Prace serwisowe",
            "status_unknown": "Nieznany status",
            "Status Page": "Strona statusu",
        ],
        "pt-BR": [
            "refresh_on_open_title": "Atualizar ao abrir o menu",
            "Refresh": "Atualizar",
            "refresh_interval_title": "Intervalo de atualização",
            "refresh_manual": "Manual",
            "refresh_1min": "1 min",
            "refresh_2min": "2 min",
            "refresh_5min": "5 min",
            "refresh_15min": "15 min",
            "refresh_30min": "30 min",
            "refresh_adaptive": "Adaptativo",
            "Quit": "Encerrar",
            "language_title": "Idioma",
            "language_system": "Sistema",
            "check_provider_status_title": "Verificar status dos provedores",
            "status_operational": "Operacional",
            "status_degraded": "Desempenho degradado",
            "status_partial_outage": "Falha parcial",
            "status_major_outage": "Falha geral",
            "status_maintenance": "Manutenção",
            "status_unknown": "Status desconhecido",
            "Status Page": "Página de status",
        ],
        "ru": [
            "refresh_on_open_title": "Обновить при открытии меню",
            "Refresh": "Обновить",
            "refresh_interval_title": "Частота обновления",
            "refresh_manual": "Вручную",
            "refresh_1min": "1 мин.",
            "refresh_2min": "2 мин",
            "refresh_5min": "5 мин.",
            "refresh_15min": "15 мин.",
            "refresh_30min": "30 мин.",
            "refresh_adaptive": "Адаптивно",
            "Quit": "Выйти",
            "language_title": "Язык",
            "language_system": "Системный",
            "check_provider_status_title": "Проверить статус провайдера",
            "status_operational": "Работает",
            "status_degraded": "Сниженная производительность",
            "status_partial_outage": "Частичный сбой",
            "status_major_outage": "Серьёзный сбой",
            "status_maintenance": "Техническое обслуживание",
            "status_unknown": "Статус неизвестен",
            "Status Page": "Страница статуса",
        ],
        "sv": [
            "refresh_on_open_title": "Uppdatera när menyn öppnas",
            "Refresh": "Uppdatera",
            "refresh_interval_title": "Uppdateringsintervall",
            "refresh_manual": "Manuellt",
            "refresh_1min": "1 min",
            "refresh_2min": "2 min",
            "refresh_5min": "5 min",
            "refresh_15min": "15 min",
            "refresh_30min": "30 min",
            "refresh_adaptive": "Adaptiv",
            "Quit": "Avsluta",
            "language_title": "Språk",
            "language_system": "System",
            "check_provider_status_title": "Kontrollera leverantörsstatus",
            "status_operational": "Fungerar normalt",
            "status_degraded": "Försämrad prestanda",
            "status_partial_outage": "Delvis avbrott",
            "status_major_outage": "Större avbrott",
            "status_maintenance": "Underhåll",
            "status_unknown": "Okänd status",
            "Status Page": "Statussida",
        ],
        "th": [
            "refresh_on_open_title": "รีเฟรชเมื่อเปิดเมนู",
            "Refresh": "รีเฟรช",
            "refresh_interval_title": "ช่วงเวลาการรีเฟรช",
            "refresh_manual": "ด้วยมือ",
            "refresh_1min": "1 นาที",
            "refresh_2min": "2 นาที",
            "refresh_5min": "5 นาที",
            "refresh_15min": "15 นาที",
            "refresh_30min": "30 นาที",
            "refresh_adaptive": "ปรับอัตโนมัติ",
            "Quit": "ออก",
            "language_title": "ภาษา",
            "language_system": "ระบบ",
            "check_provider_status_title": "ตรวจสอบสถานะผู้ให้บริการ",
            "status_operational": "การดําเนินงาน",
            "status_degraded": "ประสิทธิภาพลดลง",
            "status_partial_outage": "ไฟฟ้าดับบางส่วน",
            "status_major_outage": "ไฟฟ้าดับครั้งใหญ่",
            "status_maintenance": "ซ่อมบํารุง",
            "status_unknown": "ไม่ทราบสถานะ",
            "Status Page": "หน้าสถานะ",
        ],
        "tr": [
            "refresh_on_open_title": "Menü açıldığında yenile",
            "Refresh": "Yenile",
            "refresh_interval_title": "Yenileme aralığı",
            "refresh_manual": "El ile",
            "refresh_1min": "1 dak",
            "refresh_2min": "2 dak",
            "refresh_5min": "5 dak",
            "refresh_15min": "15 dak",
            "refresh_30min": "30 dak",
            "refresh_adaptive": "Uyarlanabilir",
            "Quit": "Çık",
            "language_title": "Dil",
            "language_system": "Sistem",
            "check_provider_status_title": "Sağlayıcı durumunu denetle",
            "status_operational": "Çalışır durumda",
            "status_degraded": "Düşük performans",
            "status_partial_outage": "Kısmi kesinti",
            "status_major_outage": "Büyük kesinti",
            "status_maintenance": "Bakım",
            "status_unknown": "Durum bilinmiyor",
            "Status Page": "Durum sayfası",
        ],
        "uk": [
            "refresh_on_open_title": "Оновлювати при відкритті меню",
            "Refresh": "Оновити",
            "refresh_interval_title": "Інтервал оновлення",
            "refresh_manual": "Інструкція",
            "refresh_1min": "1 хв",
            "refresh_2min": "2 хв",
            "refresh_5min": "5 хв",
            "refresh_15min": "15 хв",
            "refresh_30min": "30 хв",
            "refresh_adaptive": "Адаптивний",
            "Quit": "Вийти",
            "language_title": "Мова",
            "language_system": "Система",
            "check_provider_status_title": "Перевірте статус провайдера",
            "status_operational": "Працює",
            "status_degraded": "Знижена продуктивність",
            "status_partial_outage": "Часткове відключення",
            "status_major_outage": "Серйозний збій",
            "status_maintenance": "Технічне обслуговування",
            "status_unknown": "Статус невідомий",
            "Status Page": "Сторінка стану",
        ],
        "vi": [
            "refresh_on_open_title": "Làm mới khi mở menu",
            "Refresh": "Làm mới",
            "refresh_interval_title": "Khoảng thời gian làm mới",
            "refresh_manual": "Thủ công",
            "refresh_1min": "1 phút",
            "refresh_2min": "2 phút",
            "refresh_5min": "5 phút",
            "refresh_15min": "15 phút",
            "refresh_30min": "30 phút",
            "refresh_adaptive": "Thích ứng",
            "Quit": "Thoát",
            "language_title": "Ngôn ngữ",
            "language_system": "Hệ thống",
            "check_provider_status_title": "Kiểm tra Nhà cung cấp trạng thái",
            "status_operational": "Hoạt động",
            "status_degraded": "Hiệu suất giảm",
            "status_partial_outage": "Mất điện một phần",
            "status_major_outage": "Mất điện lớn",
            "status_maintenance": "Bảo trì",
            "status_unknown": "Trạng thái không xác định",
            "Status Page": "Trang trạng thái",
        ],
        "zh-Hans": [
            "refresh_on_open_title": "打开菜单时刷新",
            "Refresh": "刷新",
            "refresh_interval_title": "刷新间隔",
            "refresh_manual": "手动",
            "refresh_1min": "1 分钟",
            "refresh_2min": "2 分钟",
            "refresh_5min": "5 分钟",
            "refresh_15min": "15 分钟",
            "refresh_30min": "30 分钟",
            "refresh_adaptive": "自适应",
            "Quit": "退出",
            "language_title": "语言",
            "language_system": "跟随系统",
            "check_provider_status_title": "检查提供商状态",
            "status_operational": "正常运行",
            "status_degraded": "性能下降",
            "status_partial_outage": "部分中断",
            "status_major_outage": "重大中断",
            "status_maintenance": "维护中",
            "status_unknown": "状态未知",
            "Status Page": "状态页",
        ],
        "zh-Hant": [
            "refresh_on_open_title": "開啟選單時重新整理",
            "Refresh": "重新整理",
            "refresh_interval_title": "重新整理間隔",
            "refresh_manual": "手動",
            "refresh_1min": "1 分鐘",
            "refresh_2min": "2 分鐘",
            "refresh_5min": "5 分鐘",
            "refresh_15min": "15 分鐘",
            "refresh_30min": "30 分鐘",
            "refresh_adaptive": "自適應",
            "Quit": "結束",
            "language_title": "語言",
            "language_system": "依照系統",
            "check_provider_status_title": "檢查提供者狀態",
            "status_operational": "運作正常",
            "status_degraded": "效能下降",
            "status_partial_outage": "部分服務中斷",
            "status_major_outage": "重大服務中斷",
            "status_maintenance": "維護中",
            "status_unknown": "狀態未知",
            "Status Page": "狀態頁",
        ],
    ]
}
#endif
