#if os(Windows)
import Foundation

/// Status-only catalog copied from the original app's Localizable.strings.
/// Resolved while building menus; language changes require no new status request.
enum WindowsStatusLocalization {
    static var supportedLanguages: [String] { self.catalog.keys.sorted() }

    static func nativeName(for language: String) -> String {
        Locale(identifier: language).localizedString(forIdentifier: language) ?? language
    }

    static func text(_ key: String) -> String {
        let defaults = UserDefaults(suiteName: WindowsRefreshSettings.suiteName) ?? .standard
        let configured = defaults.string(forKey: "appLanguage")?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        let preferences = configured.isEmpty ? Locale.preferredLanguages : [configured]
        let language = Bundle.preferredLocalizations(from: self.catalog.keys.sorted(), forPreferences: preferences).first ?? "en"
        return self.catalog[language]?[key] ?? self.catalog["en"]?[key] ?? key
    }

    private static let catalog: [String: [String: String]] = [
        "ar": [
            "language_title": "اللغة",
            "language_system": "النظام",
            "check_provider_status_title": "تحقق من حالة المزود",
            "status_operational": "التشغيل",
            "status_degraded": "أداء متدهور",
            "status_partial_outage": "انقطاع جزئي",
            "status_major_outage": "انقطاع كبير",
            "status_maintenance": "الصيانة",
            "status_unknown": "الحالة غير معروفة",
            "Status Page": "صفحة الحالة",
        ],
        "ca": [
            "language_title": "Idioma",
            "language_system": "Sistema",
            "check_provider_status_title": "Comproveu l'estat del proveïdor",
            "status_operational": "Operatiu",
            "status_degraded": "Rendiment degradat",
            "status_partial_outage": "Interrupció parcial",
            "status_major_outage": "Interrupció greu",
            "status_maintenance": "Manteniment",
            "status_unknown": "Estat desconegut",
            "Status Page": "Pàgina d'estat",
        ],
        "de": [
            "language_title": "Sprache",
            "language_system": "System",
            "check_provider_status_title": "Anbieterstatus prüfen",
            "status_operational": "Betriebsbereit",
            "status_degraded": "Eingeschränkte Leistung",
            "status_partial_outage": "Teilweiser Ausfall",
            "status_major_outage": "Schwerwiegender Ausfall",
            "status_maintenance": "Wartung",
            "status_unknown": "Status unbekannt",
            "Status Page": "Statusseite",
        ],
        "en": [
            "language_title": "Language",
            "language_system": "System",
            "check_provider_status_title": "Check provider status",
            "status_operational": "Operational",
            "status_degraded": "Degraded performance",
            "status_partial_outage": "Partial outage",
            "status_major_outage": "Major outage",
            "status_maintenance": "Maintenance",
            "status_unknown": "Status unknown",
            "Status Page": "Status Page",
        ],
        "es": [
            "language_title": "Idioma",
            "language_system": "Sistema",
            "check_provider_status_title": "Comprobar estado del proveedor",
            "status_operational": "Operativo",
            "status_degraded": "Rendimiento degradado",
            "status_partial_outage": "Interrupción parcial",
            "status_major_outage": "Interrupción grave",
            "status_maintenance": "Mantenimiento",
            "status_unknown": "Estado desconocido",
            "Status Page": "Página de estado",
        ],
        "fa": [
            "language_title": "زبان",
            "language_system": "سیستم",
            "check_provider_status_title": "وضعیت ارائه دهنده را بررسی کنید",
            "status_operational": "عملیاتی",
            "status_degraded": "کارایی کاهش‌یافته",
            "status_partial_outage": "قطعی جزئی",
            "status_major_outage": "قطعی عمده",
            "status_maintenance": "نگهداری",
            "status_unknown": "وضعیت نامشخص",
            "Status Page": "صفحه وضعیت",
        ],
        "fr": [
            "language_title": "Langue",
            "language_system": "Système",
            "check_provider_status_title": "Vérifier l'état des fournisseurs",
            "status_operational": "Opérationnel",
            "status_degraded": "Performances dégradées",
            "status_partial_outage": "Dégradation partielle",
            "status_major_outage": "Panne majeure",
            "status_maintenance": "Maintenance",
            "status_unknown": "Statut inconnu",
            "Status Page": "Page d'état",
        ],
        "gl": [
            "language_title": "Idioma",
            "language_system": "Sistema",
            "check_provider_status_title": "Comprobar o estado do provedor",
            "status_operational": "Operativo",
            "status_degraded": "Rendemento degradado",
            "status_partial_outage": "Interrupción parcial",
            "status_major_outage": "Interrupción grave",
            "status_maintenance": "Mantemento",
            "status_unknown": "Estado descoñecido",
            "Status Page": "Páxina de estado",
        ],
        "id": [
            "language_title": "Bahasa",
            "language_system": "Sistem",
            "check_provider_status_title": "Periksa status penyedia",
            "status_operational": "Operasional",
            "status_degraded": "Performa menurun",
            "status_partial_outage": "Gangguan sebagian",
            "status_major_outage": "Gangguan besar",
            "status_maintenance": "Pemeliharaan",
            "status_unknown": "Status tidak diketahui",
            "Status Page": "Halaman Status",
        ],
        "it": [
            "language_title": "Lingua",
            "language_system": "Sistema",
            "check_provider_status_title": "Controlla stato provider",
            "status_operational": "Operativo",
            "status_degraded": "Prestazioni ridotte",
            "status_partial_outage": "Interruzione parziale",
            "status_major_outage": "Interruzione grave",
            "status_maintenance": "Manutenzione",
            "status_unknown": "Stato sconosciuto",
            "Status Page": "Pagina di stato",
        ],
        "ja": [
            "language_title": "言語",
            "language_system": "システム",
            "check_provider_status_title": "プロバイダのステータスを確認",
            "status_operational": "正常稼働中",
            "status_degraded": "パフォーマンス低下",
            "status_partial_outage": "一部障害",
            "status_major_outage": "重大な障害",
            "status_maintenance": "メンテナンス中",
            "status_unknown": "ステータス不明",
            "Status Page": "ステータスページ",
        ],
        "ko": [
            "language_title": "언어",
            "language_system": "시스템",
            "check_provider_status_title": "공급자 상태 확인",
            "status_operational": "정상 작동",
            "status_degraded": "성능 저하",
            "status_partial_outage": "부분 장애",
            "status_major_outage": "주요 장애",
            "status_maintenance": "유지 보수",
            "status_unknown": "상태 알 수 없음",
            "Status Page": "상태 페이지",
        ],
        "nl": [
            "language_title": "Taal",
            "language_system": "Systeem",
            "check_provider_status_title": "Controleer de status van de provider",
            "status_operational": "Operationeel",
            "status_degraded": "Verminderde prestaties",
            "status_partial_outage": "Gedeeltelijke uitval",
            "status_major_outage": "Grote storing",
            "status_maintenance": "Onderhoud",
            "status_unknown": "Status onbekend",
            "Status Page": "Statuspagina",
        ],
        "pl": [
            "language_title": "Język",
            "language_system": "System",
            "check_provider_status_title": "Sprawdzaj status dostawców",
            "status_operational": "Operacyjne",
            "status_degraded": "Obniżona wydajność",
            "status_partial_outage": "Częściowa awaria",
            "status_major_outage": "Poważna awaria",
            "status_maintenance": "Prace serwisowe",
            "status_unknown": "Nieznany status",
            "Status Page": "Strona statusu",
        ],
        "pt-BR": [
            "language_title": "Idioma",
            "language_system": "Sistema",
            "check_provider_status_title": "Verificar status dos provedores",
            "status_operational": "Operacional",
            "status_degraded": "Desempenho degradado",
            "status_partial_outage": "Falha parcial",
            "status_major_outage": "Falha geral",
            "status_maintenance": "Manutenção",
            "status_unknown": "Status desconhecido",
            "Status Page": "Página de status",
        ],
        "ru": [
            "language_title": "Язык",
            "language_system": "Системный",
            "check_provider_status_title": "Проверить статус провайдера",
            "status_operational": "Работает",
            "status_degraded": "Сниженная производительность",
            "status_partial_outage": "Частичный сбой",
            "status_major_outage": "Серьёзный сбой",
            "status_maintenance": "Техническое обслуживание",
            "status_unknown": "Статус неизвестен",
            "Status Page": "Страница статуса",
        ],
        "sv": [
            "language_title": "Språk",
            "language_system": "System",
            "check_provider_status_title": "Kontrollera leverantörsstatus",
            "status_operational": "Fungerar normalt",
            "status_degraded": "Försämrad prestanda",
            "status_partial_outage": "Delvis avbrott",
            "status_major_outage": "Större avbrott",
            "status_maintenance": "Underhåll",
            "status_unknown": "Okänd status",
            "Status Page": "Statussida",
        ],
        "th": [
            "language_title": "ภาษา",
            "language_system": "ระบบ",
            "check_provider_status_title": "ตรวจสอบสถานะผู้ให้บริการ",
            "status_operational": "การดําเนินงาน",
            "status_degraded": "ประสิทธิภาพลดลง",
            "status_partial_outage": "ไฟฟ้าดับบางส่วน",
            "status_major_outage": "ไฟฟ้าดับครั้งใหญ่",
            "status_maintenance": "ซ่อมบํารุง",
            "status_unknown": "ไม่ทราบสถานะ",
            "Status Page": "หน้าสถานะ",
        ],
        "tr": [
            "language_title": "Dil",
            "language_system": "Sistem",
            "check_provider_status_title": "Sağlayıcı durumunu denetle",
            "status_operational": "Çalışır durumda",
            "status_degraded": "Düşük performans",
            "status_partial_outage": "Kısmi kesinti",
            "status_major_outage": "Büyük kesinti",
            "status_maintenance": "Bakım",
            "status_unknown": "Durum bilinmiyor",
            "Status Page": "Durum sayfası",
        ],
        "uk": [
            "language_title": "Мова",
            "language_system": "Система",
            "check_provider_status_title": "Перевірте статус провайдера",
            "status_operational": "Працює",
            "status_degraded": "Знижена продуктивність",
            "status_partial_outage": "Часткове відключення",
            "status_major_outage": "Серйозний збій",
            "status_maintenance": "Технічне обслуговування",
            "status_unknown": "Статус невідомий",
            "Status Page": "Сторінка стану",
        ],
        "vi": [
            "language_title": "Ngôn ngữ",
            "language_system": "Hệ thống",
            "check_provider_status_title": "Kiểm tra Nhà cung cấp trạng thái",
            "status_operational": "Hoạt động",
            "status_degraded": "Hiệu suất giảm",
            "status_partial_outage": "Mất điện một phần",
            "status_major_outage": "Mất điện lớn",
            "status_maintenance": "Bảo trì",
            "status_unknown": "Trạng thái không xác định",
            "Status Page": "Trang trạng thái",
        ],
        "zh-Hans": [
            "language_title": "语言",
            "language_system": "跟随系统",
            "check_provider_status_title": "检查提供商状态",
            "status_operational": "正常运行",
            "status_degraded": "性能下降",
            "status_partial_outage": "部分中断",
            "status_major_outage": "重大中断",
            "status_maintenance": "维护中",
            "status_unknown": "状态未知",
            "Status Page": "状态页",
        ],
        "zh-Hant": [
            "language_title": "語言",
            "language_system": "依照系統",
            "check_provider_status_title": "檢查提供者狀態",
            "status_operational": "運作正常",
            "status_degraded": "效能下降",
            "status_partial_outage": "部分服務中斷",
            "status_major_outage": "重大服務中斷",
            "status_maintenance": "維護中",
            "status_unknown": "狀態未知",
            "Status Page": "狀態頁",
        ],
    ]
}
#endif
