#if os(Windows)
import Foundation

/// Incremental Windows menu catalog copied from the original app's Localizable.strings.
/// Resolved while building menus; language changes require no new status request.
enum WindowsStatusLocalization {
    static var supportedLanguages: [String] { self.catalog.keys.sorted() }

    static func nativeName(for language: String) -> String {
        Locale(identifier: language).localizedString(forIdentifier: language) ?? language
    }

    static func text(_ key: String) -> String {
        let defaults = UserDefaults(suiteName: WindowsRefreshSettings.suiteName) ?? .standard
        let configured = defaults.string(forKey: "appLanguage")?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        let preferences = configured.isEmpty ? Locale.preferredLanguages : [configured]
        let language = Bundle.preferredLocalizations(from: self.catalog.keys.sorted(), forPreferences: preferences).first ?? "en"
        return self.catalog[language]?[key] ?? self.catalog["en"]?[key] ?? key
    }

    private static let catalog: [String: [String: String]] = [
        "ar": [
            "Historical tracking": "التتبع التاريخي",
            "Show reset time as clock": "عرض وقت إعادة التعيين كساعة",
            "Show usage as used": "استخدام العرض كما هو مستخدم",
            "quota_depleted_title": "نفاد الحصة واستعادتها",
            "threshold_warnings_title": "تحذيرات العتبة",
            "predictive_pace_warnings_title": "تحذيرات تنبؤية للوتيرة",
            "quota_warning_sound": "تشغيل صوت الإشعار",
            "show_credits_extra_usage_title": "اعتمادات العرض + الاستخدام الإضافي",
            "hide_personal_info_title": "إخفاء المعلومات الشخصية",
            "refresh_on_open_title": "التحديث عند فتح القائمة",
            "Refresh": "تحديث",
            "refresh_interval_title": "فاصل التحديث",
            "refresh_manual": "الدليل",
            "refresh_1min": "دقيقة واحدة",
            "refresh_2min": "دقيقتان",
            "refresh_5min": "5 دقائق",
            "refresh_15min": "15 دقيقة",
            "refresh_30min": "30 دقيقة",
            "refresh_adaptive": "تكيفي",
            "Quit": "استقال",
            "language_title": "اللغة",
            "language_system": "النظام",
            "check_provider_status_title": "تحقق من حالة المزود",
            "status_operational": "التشغيل",
            "status_degraded": "أداء متدهور",
            "status_partial_outage": "انقطاع جزئي",
            "status_major_outage": "انقطاع كبير",
            "status_maintenance": "الصيانة",
            "status_unknown": "الحالة غير معروفة",
            "Status Page": "صفحة الحالة",
        ],
        "ca": [
            "Historical tracking": "Seguiment històric",
            "Show reset time as clock": "Mostreu l'hora de reinici com a rellotge",
            "Show usage as used": "Mostreu l'ús com a consumit",
            "quota_depleted_title": "Quota esgotada i restablerta",
            "threshold_warnings_title": "Avisos de llindar",
            "quota_warning_sound": "Reprodueix el so de notificació",
            "show_credits_extra_usage_title": "Mostreu crèdits + ús addicional",
            "hide_personal_info_title": "Amagueu la informació personal",
            "predictive_pace_warnings_title": "Alertes predictives de ritme",
            "refresh_on_open_title": "Actualitza en obrir el menú",
            "Refresh": "Actualitza",
            "refresh_interval_title": "Interval d'actualització",
            "refresh_manual": "Manual",
            "refresh_1min": "1 min",
            "refresh_2min": "2 min",
            "refresh_5min": "5 min",
            "refresh_15min": "15 min",
            "refresh_30min": "30 min",
            "refresh_adaptive": "Adaptatiu",
            "Quit": "Sortiu",
            "language_title": "Idioma",
            "language_system": "Sistema",
            "check_provider_status_title": "Comproveu l'estat del proveïdor",
            "status_operational": "Operatiu",
            "status_degraded": "Rendiment degradat",
            "status_partial_outage": "Interrupció parcial",
            "status_major_outage": "Interrupció greu",
            "status_maintenance": "Manteniment",
            "status_unknown": "Estat desconegut",
            "Status Page": "Pàgina d'estat",
        ],
        "de": [
            "Historical tracking": "Historische Verfolgung",
            "Show reset time as clock": "Reset-Zeit als Uhr anzeigen",
            "Show usage as used": "Nutzung als verbraucht anzeigen",
            "quota_depleted_title": "Kontingent erschöpft und wiederhergestellt",
            "threshold_warnings_title": "Schwellenwertwarnungen",
            "predictive_pace_warnings_title": "Vorausschauende Tempo-Warnungen",
            "quota_warning_sound": "Benachrichtigungston abspielen",
            "show_credits_extra_usage_title": "Credits + zusätzliche Nutzung anzeigen",
            "hide_personal_info_title": "Persönliche Informationen ausblenden",
            "refresh_on_open_title": "Beim Öffnen des Menüs aktualisieren",
            "Refresh": "Aktualisieren",
            "refresh_interval_title": "Aktualisierungsintervall",
            "refresh_manual": "Manuell",
            "refresh_1min": "1 Minute",
            "refresh_2min": "2 Min",
            "refresh_5min": "5 Min",
            "refresh_15min": "15 Min",
            "refresh_30min": "30 Min",
            "refresh_adaptive": "Adaptiv",
            "Quit": "Beenden",
            "language_title": "Sprache",
            "language_system": "System",
            "check_provider_status_title": "Anbieterstatus prüfen",
            "status_operational": "Betriebsbereit",
            "status_degraded": "Eingeschränkte Leistung",
            "status_partial_outage": "Teilweiser Ausfall",
            "status_major_outage": "Schwerwiegender Ausfall",
            "status_maintenance": "Wartung",
            "status_unknown": "Status unbekannt",
            "Status Page": "Statusseite",
        ],
        "en": [
            "Historical tracking": "Historical tracking",
            "Show reset time as clock": "Show reset time as clock",
            "Show usage as used": "Show usage as used",
            "quota_depleted_title": "Quota depleted & restored",
            "threshold_warnings_title": "Threshold warnings",
            "predictive_pace_warnings_title": "Pace warnings",
            "quota_warning_sound": "Play notification sound",
            "show_credits_extra_usage_title": "Show credits & extra usage",
            "hide_personal_info_title": "Hide personal information",
            "refresh_on_open_title": "Refresh when the menu opens",
            "Refresh": "Refresh",
            "refresh_interval_title": "Refresh interval",
            "refresh_manual": "Manual",
            "refresh_1min": "1 min",
            "refresh_2min": "2 min",
            "refresh_5min": "5 min",
            "refresh_15min": "15 min",
            "refresh_30min": "30 min",
            "refresh_adaptive": "Adaptive",
            "Quit": "Quit",
            "language_title": "Language",
            "language_system": "System",
            "check_provider_status_title": "Check provider status",
            "status_operational": "Operational",
            "status_degraded": "Degraded performance",
            "status_partial_outage": "Partial outage",
            "status_major_outage": "Major outage",
            "status_maintenance": "Maintenance",
            "status_unknown": "Status unknown",
            "Status Page": "Status Page",
        ],
        "es": [
            "Historical tracking": "Seguimiento histórico",
            "Show reset time as clock": "Mostrar la hora de reinicio como reloj",
            "Show usage as used": "Mostrar el uso como consumido",
            "quota_depleted_title": "Cuota agotada y restaurada",
            "threshold_warnings_title": "Avisos de umbral",
            "predictive_pace_warnings_title": "Avisos predictivos de ritmo",
            "quota_warning_sound": "Reproducir sonido de notificación",
            "show_credits_extra_usage_title": "Mostrar créditos + uso adicional",
            "hide_personal_info_title": "Ocultar información personal",
            "refresh_on_open_title": "Actualizar al abrir el menú",
            "Refresh": "Actualizar",
            "refresh_interval_title": "Intervalo de actualización",
            "refresh_manual": "Manual",
            "refresh_1min": "1 min",
            "refresh_2min": "2 min",
            "refresh_5min": "5 min",
            "refresh_15min": "15 min",
            "refresh_30min": "30 min",
            "refresh_adaptive": "Adaptativo",
            "Quit": "Salir",
            "language_title": "Idioma",
            "language_system": "Sistema",
            "check_provider_status_title": "Comprobar estado del proveedor",
            "status_operational": "Operativo",
            "status_degraded": "Rendimiento degradado",
            "status_partial_outage": "Interrupción parcial",
            "status_major_outage": "Interrupción grave",
            "status_maintenance": "Mantenimiento",
            "status_unknown": "Estado desconocido",
            "Status Page": "Página de estado",
        ],
        "fa": [
            "Historical tracking": "ردیابی تاریخی",
            "Show reset time as clock": "نمایش زمان بازنشانی به صورت ساعت",
            "Show usage as used": "کاربرد نمایش همان طور که استفاده می شود",
            "quota_depleted_title": "اتمام و بازیابی سهمیه",
            "threshold_warnings_title": "هشدارهای آستانه",
            "predictive_pace_warnings_title": "هشدارهای پیش‌بینی روند مصرف",
            "quota_warning_sound": "صدای اعلان پخش کن",
            "show_credits_extra_usage_title": "نمایش اعتبارها + استفاده اضافی",
            "hide_personal_info_title": "مخفی کردن اطلاعات شخصی",
            "refresh_on_open_title": "بازخوانی هنگام باز کردن منو",
            "Refresh": "تازه سازی",
            "refresh_interval_title": "فاصله تازه‌سازی",
            "refresh_manual": "دفترچه راهنما",
            "refresh_1min": "۱ دقیقه",
            "refresh_2min": "۲ دقیقه",
            "refresh_5min": "۵ دقیقه",
            "refresh_15min": "۱۵ دقیقه",
            "refresh_30min": "۳۰ دقیقه",
            "refresh_adaptive": "تطبیقی",
            "Quit": "ترک کن",
            "language_title": "زبان",
            "language_system": "سیستم",
            "check_provider_status_title": "وضعیت ارائه دهنده را بررسی کنید",
            "status_operational": "عملیاتی",
            "status_degraded": "کارایی کاهش‌یافته",
            "status_partial_outage": "قطعی جزئی",
            "status_major_outage": "قطعی عمده",
            "status_maintenance": "نگهداری",
            "status_unknown": "وضعیت نامشخص",
            "Status Page": "صفحه وضعیت",
        ],
        "fr": [
            "Historical tracking": "Suivi historique",
            "Show reset time as clock": "Afficher l'heure de réinitialisation sous forme d'horloge",
            "Show usage as used": "Afficher l'utilisation telle qu'utilisée",
            "quota_depleted_title": "Quota épuisé et rétabli",
            "threshold_warnings_title": "Alertes de seuil",
            "predictive_pace_warnings_title": "Avertissements prédictifs de rythme",
            "quota_warning_sound": "Lire un son de notification",
            "show_credits_extra_usage_title": "Afficher les crédits + utilisation supplémentaire",
            "hide_personal_info_title": "Masquer les informations personnelles",
            "refresh_on_open_title": "Actualiser à l'ouverture du menu",
            "Refresh": "Actualiser",
            "refresh_interval_title": "Intervalle d’actualisation",
            "refresh_manual": "Manuel",
            "refresh_1min": "1 minute",
            "refresh_2min": "2 minutes",
            "refresh_5min": "5 minutes",
            "refresh_15min": "15 minutes",
            "refresh_30min": "30 minutes",
            "refresh_adaptive": "Adaptatif",
            "Quit": "Quitter",
            "language_title": "Langue",
            "language_system": "Système",
            "check_provider_status_title": "Vérifier l'état des fournisseurs",
            "status_operational": "Opérationnel",
            "status_degraded": "Performances dégradées",
            "status_partial_outage": "Dégradation partielle",
            "status_major_outage": "Panne majeure",
            "status_maintenance": "Maintenance",
            "status_unknown": "Statut inconnu",
            "Status Page": "Page d'état",
        ],
        "gl": [
            "Historical tracking": "Seguimento histórico",
            "Show reset time as clock": "Amosar a hora de reinicio como reloxo",
            "Show usage as used": "Amosar o uso como consumido",
            "quota_depleted_title": "Cota esgotada e restaurada",
            "threshold_warnings_title": "Avisos de limiar",
            "quota_warning_sound": "Reproducir o son de notificación",
            "show_credits_extra_usage_title": "Amosar créditos + uso adicional",
            "hide_personal_info_title": "Ocultar información persoal",
            "predictive_pace_warnings_title": "Avisos preditivos de ritmo",
            "refresh_on_open_title": "Actualizar ao abrir o menú",
            "Refresh": "Actualizar",
            "refresh_interval_title": "Intervalo de actualización",
            "refresh_manual": "Manual",
            "refresh_1min": "1 min",
            "refresh_2min": "2 min",
            "refresh_5min": "5 min",
            "refresh_15min": "15 min",
            "refresh_30min": "30 min",
            "Quit": "Saír",
            "refresh_adaptive": "Adaptativa",
            "language_title": "Idioma",
            "language_system": "Sistema",
            "check_provider_status_title": "Comprobar o estado do provedor",
            "status_operational": "Operativo",
            "status_degraded": "Rendemento degradado",
            "status_partial_outage": "Interrupción parcial",
            "status_major_outage": "Interrupción grave",
            "status_maintenance": "Mantemento",
            "status_unknown": "Estado descoñecido",
            "Status Page": "Páxina de estado",
        ],
        "id": [
            "Historical tracking": "Pelacakan riwayat",
            "Show reset time as clock": "Tampilkan waktu reset sebagai jam",
            "Show usage as used": "Tampilkan penggunaan sebagai terpakai",
            "quota_depleted_title": "Kuota habis & tersedia kembali",
            "threshold_warnings_title": "Peringatan ambang batas",
            "predictive_pace_warnings_title": "Peringatan prediktif laju pemakaian",
            "quota_warning_sound": "Mainkan suara notifikasi",
            "show_credits_extra_usage_title": "Tampilkan kredit + penggunaan ekstra",
            "hide_personal_info_title": "Sembunyikan informasi pribadi",
            "refresh_on_open_title": "Segarkan saat menu dibuka",
            "Refresh": "Segarkan",
            "refresh_interval_title": "Interval penyegaran",
            "refresh_manual": "Manual",
            "refresh_1min": "1 mnt",
            "refresh_2min": "2 mnt",
            "refresh_5min": "5 mnt",
            "refresh_15min": "15 mnt",
            "refresh_30min": "30 mnt",
            "refresh_adaptive": "Adaptif",
            "Quit": "Keluar",
            "language_title": "Bahasa",
            "language_system": "Sistem",
            "check_provider_status_title": "Periksa status penyedia",
            "status_operational": "Operasional",
            "status_degraded": "Performa menurun",
            "status_partial_outage": "Gangguan sebagian",
            "status_major_outage": "Gangguan besar",
            "status_maintenance": "Pemeliharaan",
            "status_unknown": "Status tidak diketahui",
            "Status Page": "Halaman Status",
        ],
        "it": [
            "Historical tracking": "Tracciamento storico",
            "Show reset time as clock": "Mostra l'ora di reset come orario",
            "Show usage as used": "Mostra l'utilizzo come consumato",
            "quota_depleted_title": "Quota esaurita e ripristinata",
            "threshold_warnings_title": "Avvisi di soglia",
            "predictive_pace_warnings_title": "Avvisi predittivi sul ritmo",
            "quota_warning_sound": "Riproduci suono di notifica",
            "show_credits_extra_usage_title": "Mostra crediti + uso extra",
            "hide_personal_info_title": "Nascondi informazioni personali",
            "refresh_on_open_title": "Aggiorna all'apertura del menu",
            "Refresh": "Aggiorna",
            "refresh_interval_title": "Intervallo di aggiornamento",
            "refresh_manual": "Manuale",
            "refresh_1min": "1 min.",
            "refresh_2min": "2 min.",
            "refresh_5min": "5 min.",
            "refresh_15min": "15 min.",
            "refresh_30min": "30 min.",
            "refresh_adaptive": "Adattivo",
            "Quit": "Esci",
            "language_title": "Lingua",
            "language_system": "Sistema",
            "check_provider_status_title": "Controlla stato provider",
            "status_operational": "Operativo",
            "status_degraded": "Prestazioni ridotte",
            "status_partial_outage": "Interruzione parziale",
            "status_major_outage": "Interruzione grave",
            "status_maintenance": "Manutenzione",
            "status_unknown": "Stato sconosciuto",
            "Status Page": "Pagina di stato",
        ],
        "ja": [
            "Historical tracking": "履歴トラッキング",
            "Show reset time as clock": "リセット時刻を時計表示",
            "Show usage as used": "使用量を消費分で表示",
            "quota_depleted_title": "クォータの枯渇と回復",
            "threshold_warnings_title": "しきい値警告",
            "predictive_pace_warnings_title": "予測ペース警告",
            "quota_warning_sound": "通知音を再生",
            "show_credits_extra_usage_title": "クレジットと追加使用量を表示",
            "hide_personal_info_title": "個人情報を隠す",
            "refresh_on_open_title": "メニューを開いたときに更新",
            "Refresh": "更新",
            "refresh_interval_title": "更新間隔",
            "refresh_manual": "手動",
            "refresh_1min": "1分",
            "refresh_2min": "2分",
            "refresh_5min": "5分",
            "refresh_15min": "15分",
            "refresh_30min": "30分",
            "refresh_adaptive": "アダプティブ",
            "Quit": "終了",
            "language_title": "言語",
            "language_system": "システム",
            "check_provider_status_title": "プロバイダのステータスを確認",
            "status_operational": "正常稼働中",
            "status_degraded": "パフォーマンス低下",
            "status_partial_outage": "一部障害",
            "status_major_outage": "重大な障害",
            "status_maintenance": "メンテナンス中",
            "status_unknown": "ステータス不明",
            "Status Page": "ステータスページ",
        ],
        "ko": [
            "Historical tracking": "기록 추적",
            "Show reset time as clock": "재설정 시간을 시계로 표시",
            "Show usage as used": "사용량을 사용한 양으로 표시",
            "quota_depleted_title": "할당량 소진 및 복원",
            "threshold_warnings_title": "임곗값 경고",
            "predictive_pace_warnings_title": "예측 속도 경고",
            "quota_warning_sound": "알림 소리 재생",
            "show_credits_extra_usage_title": "크레딧 + 추가 사용량 표시",
            "hide_personal_info_title": "개인 정보 가리기",
            "refresh_on_open_title": "메뉴를 열 때 새로 고침",
            "Refresh": "새로 고침",
            "refresh_interval_title": "새로 고침 주기",
            "refresh_manual": "수동",
            "refresh_1min": "1분",
            "refresh_2min": "2분",
            "refresh_5min": "5분",
            "refresh_15min": "15분",
            "refresh_30min": "30분",
            "refresh_adaptive": "적응형",
            "Quit": "종료",
            "language_title": "언어",
            "language_system": "시스템",
            "check_provider_status_title": "공급자 상태 확인",
            "status_operational": "정상 작동",
            "status_degraded": "성능 저하",
            "status_partial_outage": "부분 장애",
            "status_major_outage": "주요 장애",
            "status_maintenance": "유지 보수",
            "status_unknown": "상태 알 수 없음",
            "Status Page": "상태 페이지",
        ],
        "nl": [
            "Historical tracking": "Historische tracking",
            "Show reset time as clock": "Toon resettijd als klok",
            "Show usage as used": "Toon gebruik zoals gebruikt",
            "quota_depleted_title": "Quotum uitgeput en hersteld",
            "threshold_warnings_title": "Drempelwaarschuwingen",
            "predictive_pace_warnings_title": "Voorspellende tempowaarschuwingen",
            "quota_warning_sound": "Meldingsgeluid afspelen",
            "show_credits_extra_usage_title": "Toon credits + extra gebruik",
            "hide_personal_info_title": "Verberg persoonlijke informatie",
            "refresh_on_open_title": "Vernieuwen bij openen van menu",
            "Refresh": "Vernieuwen",
            "refresh_interval_title": "Vernieuwingsinterval",
            "refresh_manual": "Handmatig",
            "refresh_1min": "1 min",
            "refresh_2min": "2 minuten",
            "refresh_5min": "5 min",
            "refresh_15min": "15 minuten",
            "refresh_30min": "30 min",
            "refresh_adaptive": "Adaptief",
            "Quit": "Stoppen",
            "language_title": "Taal",
            "language_system": "Systeem",
            "check_provider_status_title": "Controleer de status van de provider",
            "status_operational": "Operationeel",
            "status_degraded": "Verminderde prestaties",
            "status_partial_outage": "Gedeeltelijke uitval",
            "status_major_outage": "Grote storing",
            "status_maintenance": "Onderhoud",
            "status_unknown": "Status onbekend",
            "Status Page": "Statuspagina",
        ],
        "pl": [
            "Historical tracking": "Śledzenie historyczne",
            "Show reset time as clock": "Pokaż czas resetu jako godzinę",
            "Show usage as used": "Pokazuj użycie jako wykorzystane",
            "quota_depleted_title": "Wyczerpanie i przywrócenie limitu",
            "threshold_warnings_title": "Ostrzeżenia progowe",
            "predictive_pace_warnings_title": "Predykcyjne ostrzeżenia tempa",
            "quota_warning_sound": "Odtwarzaj dźwięk powiadomienia",
            "show_credits_extra_usage_title": "Pokaż kredyty + dodatkowe użycie",
            "hide_personal_info_title": "Ukryj dane osobowe",
            "refresh_on_open_title": "Odśwież po otwarciu menu",
            "Refresh": "Odśwież",
            "refresh_interval_title": "Częstotliwość odświeżania",
            "refresh_manual": "Ręcznie",
            "refresh_1min": "Co 1 min",
            "refresh_2min": "Co 2 min",
            "refresh_5min": "Co 5 min",
            "refresh_15min": "Co 15 min",
            "refresh_30min": "Co 30 min",
            "refresh_adaptive": "Adaptacyjny",
            "Quit": "Zakończ",
            "language_title": "Język",
            "language_system": "System",
            "check_provider_status_title": "Sprawdzaj status dostawców",
            "status_operational": "Operacyjne",
            "status_degraded": "Obniżona wydajność",
            "status_partial_outage": "Częściowa awaria",
            "status_major_outage": "Poważna awaria",
            "status_maintenance": "Prace serwisowe",
            "status_unknown": "Nieznany status",
            "Status Page": "Strona statusu",
        ],
        "pt-BR": [
            "Historical tracking": "Acompanhamento histórico",
            "Show reset time as clock": "Mostrar renovação como horário",
            "Show usage as used": "Mostrar uso como consumido",
            "quota_depleted_title": "Cota esgotada e restaurada",
            "threshold_warnings_title": "Alertas de limite",
            "predictive_pace_warnings_title": "Alertas preditivos de ritmo",
            "quota_warning_sound": "Reproduzir som de notificação",
            "show_credits_extra_usage_title": "Mostrar créditos + uso extra",
            "hide_personal_info_title": "Ocultar informações pessoais",
            "refresh_on_open_title": "Atualizar ao abrir o menu",
            "Refresh": "Atualizar",
            "refresh_interval_title": "Intervalo de atualização",
            "refresh_manual": "Manual",
            "refresh_1min": "1 min",
            "refresh_2min": "2 min",
            "refresh_5min": "5 min",
            "refresh_15min": "15 min",
            "refresh_30min": "30 min",
            "refresh_adaptive": "Adaptativo",
            "Quit": "Encerrar",
            "language_title": "Idioma",
            "language_system": "Sistema",
            "check_provider_status_title": "Verificar status dos provedores",
            "status_operational": "Operacional",
            "status_degraded": "Desempenho degradado",
            "status_partial_outage": "Falha parcial",
            "status_major_outage": "Falha geral",
            "status_maintenance": "Manutenção",
            "status_unknown": "Status desconhecido",
            "Status Page": "Página de status",
        ],
        "ru": [
            "Historical tracking": "История использования",
            "Show reset time as clock": "Показывать время сброса в виде часов",
            "Show usage as used": "Показывать израсходованное",
            "quota_depleted_title": "Исчерпание и восстановление квоты",
            "threshold_warnings_title": "Предупреждения о порогах",
            "predictive_pace_warnings_title": "Прогнозные предупреждения о темпе",
            "quota_warning_sound": "Воспроизвести звук уведомления",
            "show_credits_extra_usage_title": "Показывать кредиты и доп. использование",
            "hide_personal_info_title": "Скрыть личную информацию",
            "refresh_on_open_title": "Обновить при открытии меню",
            "Refresh": "Обновить",
            "refresh_interval_title": "Частота обновления",
            "refresh_manual": "Вручную",
            "refresh_1min": "1 мин.",
            "refresh_2min": "2 мин",
            "refresh_5min": "5 мин.",
            "refresh_15min": "15 мин.",
            "refresh_30min": "30 мин.",
            "refresh_adaptive": "Адаптивно",
            "Quit": "Выйти",
            "language_title": "Язык",
            "language_system": "Системный",
            "check_provider_status_title": "Проверить статус провайдера",
            "status_operational": "Работает",
            "status_degraded": "Сниженная производительность",
            "status_partial_outage": "Частичный сбой",
            "status_major_outage": "Серьёзный сбой",
            "status_maintenance": "Техническое обслуживание",
            "status_unknown": "Статус неизвестен",
            "Status Page": "Страница статуса",
        ],
        "sv": [
            "Historical tracking": "Historisk spårning",
            "Show reset time as clock": "Visa återställningstid som klockslag",
            "Show usage as used": "Visa användning som förbrukad",
            "quota_depleted_title": "Kvoten tar slut och återställs",
            "threshold_warnings_title": "Tröskelvarningar",
            "predictive_pace_warnings_title": "Förutsägande taktvarningar",
            "quota_warning_sound": "Spela aviseringsljud",
            "show_credits_extra_usage_title": "Visa krediter och extra användning",
            "hide_personal_info_title": "Dölj personuppgifter",
            "refresh_on_open_title": "Uppdatera när menyn öppnas",
            "Refresh": "Uppdatera",
            "refresh_interval_title": "Uppdateringsintervall",
            "refresh_manual": "Manuellt",
            "refresh_1min": "1 min",
            "refresh_2min": "2 min",
            "refresh_5min": "5 min",
            "refresh_15min": "15 min",
            "refresh_30min": "30 min",
            "refresh_adaptive": "Adaptiv",
            "Quit": "Avsluta",
            "language_title": "Språk",
            "language_system": "System",
            "check_provider_status_title": "Kontrollera leverantörsstatus",
            "status_operational": "Fungerar normalt",
            "status_degraded": "Försämrad prestanda",
            "status_partial_outage": "Delvis avbrott",
            "status_major_outage": "Större avbrott",
            "status_maintenance": "Underhåll",
            "status_unknown": "Okänd status",
            "Status Page": "Statussida",
        ],
        "th": [
            "Historical tracking": "การติดตามในอดีต",
            "Show reset time as clock": "แสดงเวลารีเซ็ตเป็นนาฬิกา",
            "Show usage as used": "แสดงการใช้งานตามที่ใช้",
            "quota_depleted_title": "โควต้าหมดและกลับมาใช้งานได้",
            "threshold_warnings_title": "คำเตือนตามเกณฑ์",
            "predictive_pace_warnings_title": "คำเตือนความเร็วการใช้เชิงคาดการณ์",
            "quota_warning_sound": "เล่นเสียงแจ้งเตือน",
            "show_credits_extra_usage_title": "แสดงเครดิต + การใช้งานเพิ่มเติม",
            "hide_personal_info_title": "ซ่อนข้อมูลส่วนบุคคล",
            "refresh_on_open_title": "รีเฟรชเมื่อเปิดเมนู",
            "Refresh": "รีเฟรช",
            "refresh_interval_title": "ช่วงเวลาการรีเฟรช",
            "refresh_manual": "ด้วยมือ",
            "refresh_1min": "1 นาที",
            "refresh_2min": "2 นาที",
            "refresh_5min": "5 นาที",
            "refresh_15min": "15 นาที",
            "refresh_30min": "30 นาที",
            "refresh_adaptive": "ปรับอัตโนมัติ",
            "Quit": "ออก",
            "language_title": "ภาษา",
            "language_system": "ระบบ",
            "check_provider_status_title": "ตรวจสอบสถานะผู้ให้บริการ",
            "status_operational": "การดําเนินงาน",
            "status_degraded": "ประสิทธิภาพลดลง",
            "status_partial_outage": "ไฟฟ้าดับบางส่วน",
            "status_major_outage": "ไฟฟ้าดับครั้งใหญ่",
            "status_maintenance": "ซ่อมบํารุง",
            "status_unknown": "ไม่ทราบสถานะ",
            "Status Page": "หน้าสถานะ",
        ],
        "tr": [
            "Historical tracking": "Geçmiş takibi",
            "Show reset time as clock": "Sıfırlama süresini saat olarak göster",
            "Show usage as used": "Kullanımı kullanılan miktar olarak göster",
            "quota_depleted_title": "Kota tükenmesi ve yenilenmesi",
            "threshold_warnings_title": "Eşik uyarıları",
            "predictive_pace_warnings_title": "Tahmini tempo uyarıları",
            "quota_warning_sound": "Bildirim sesi çal",
            "show_credits_extra_usage_title": "Krediler + ek kullanımı göster",
            "hide_personal_info_title": "Kişisel bilgileri gizle",
            "refresh_on_open_title": "Menü açıldığında yenile",
            "Refresh": "Yenile",
            "refresh_interval_title": "Yenileme aralığı",
            "refresh_manual": "El ile",
            "refresh_1min": "1 dak",
            "refresh_2min": "2 dak",
            "refresh_5min": "5 dak",
            "refresh_15min": "15 dak",
            "refresh_30min": "30 dak",
            "refresh_adaptive": "Uyarlanabilir",
            "Quit": "Çık",
            "language_title": "Dil",
            "language_system": "Sistem",
            "check_provider_status_title": "Sağlayıcı durumunu denetle",
            "status_operational": "Çalışır durumda",
            "status_degraded": "Düşük performans",
            "status_partial_outage": "Kısmi kesinti",
            "status_major_outage": "Büyük kesinti",
            "status_maintenance": "Bakım",
            "status_unknown": "Durum bilinmiyor",
            "Status Page": "Durum sayfası",
        ],
        "uk": [
            "Historical tracking": "Історичне відстеження",
            "Show reset time as clock": "Показувати час скидання як годинник",
            "Show usage as used": "Показати використання як використане",
            "quota_depleted_title": "Вичерпання та відновлення квоти",
            "threshold_warnings_title": "Попередження про порогові значення",
            "predictive_pace_warnings_title": "Прогнозні попередження про темп",
            "quota_warning_sound": "Відтворити звук сповіщення",
            "show_credits_extra_usage_title": "Показати кредити + додаткове використання",
            "hide_personal_info_title": "Приховати особисту інформацію",
            "refresh_on_open_title": "Оновлювати при відкритті меню",
            "Refresh": "Оновити",
            "refresh_interval_title": "Інтервал оновлення",
            "refresh_manual": "Інструкція",
            "refresh_1min": "1 хв",
            "refresh_2min": "2 хв",
            "refresh_5min": "5 хв",
            "refresh_15min": "15 хв",
            "refresh_30min": "30 хв",
            "refresh_adaptive": "Адаптивний",
            "Quit": "Вийти",
            "language_title": "Мова",
            "language_system": "Система",
            "check_provider_status_title": "Перевірте статус провайдера",
            "status_operational": "Працює",
            "status_degraded": "Знижена продуктивність",
            "status_partial_outage": "Часткове відключення",
            "status_major_outage": "Серйозний збій",
            "status_maintenance": "Технічне обслуговування",
            "status_unknown": "Статус невідомий",
            "Status Page": "Сторінка стану",
        ],
        "vi": [
            "Historical tracking": "Theo dõi lịch sử",
            "Show reset time as clock": "Hiển thị thời gian Đặt lại dưới dạng đồng hồ",
            "Show usage as used": "Hiển thị Mức sử dụng như đã sử dụng",
            "quota_depleted_title": "Hạn mức đã cạn & được khôi phục",
            "threshold_warnings_title": "Cảnh báo ngưỡng",
            "predictive_pace_warnings_title": "Cảnh báo nhịp dùng dự đoán",
            "quota_warning_sound": "Phát âm thanh thông báo",
            "show_credits_extra_usage_title": "Hiển thị tín dụng + phần Mức sử dụng",
            "hide_personal_info_title": "Ẩn thông tin cá nhân",
            "refresh_on_open_title": "Làm mới khi mở menu",
            "Refresh": "Làm mới",
            "refresh_interval_title": "Khoảng thời gian làm mới",
            "refresh_manual": "Thủ công",
            "refresh_1min": "1 phút",
            "refresh_2min": "2 phút",
            "refresh_5min": "5 phút",
            "refresh_15min": "15 phút",
            "refresh_30min": "30 phút",
            "refresh_adaptive": "Thích ứng",
            "Quit": "Thoát",
            "language_title": "Ngôn ngữ",
            "language_system": "Hệ thống",
            "check_provider_status_title": "Kiểm tra Nhà cung cấp trạng thái",
            "status_operational": "Hoạt động",
            "status_degraded": "Hiệu suất giảm",
            "status_partial_outage": "Mất điện một phần",
            "status_major_outage": "Mất điện lớn",
            "status_maintenance": "Bảo trì",
            "status_unknown": "Trạng thái không xác định",
            "Status Page": "Trang trạng thái",
        ],
        "zh-Hans": [
            "Historical tracking": "历史跟踪",
            "Show reset time as clock": "将重置时间显示为时钟",
            "Show usage as used": "显示已使用用量",
            "quota_depleted_title": "配额耗尽与恢复",
            "threshold_warnings_title": "阈值预警",
            "quota_warning_sound": "播放通知声音",
            "show_credits_extra_usage_title": "显示额度 + 额外用量",
            "hide_personal_info_title": "隐藏个人信息",
            "predictive_pace_warnings_title": "预测性节奏预警",
            "refresh_on_open_title": "打开菜单时刷新",
            "Refresh": "刷新",
            "refresh_interval_title": "刷新间隔",
            "refresh_manual": "手动",
            "refresh_1min": "1 分钟",
            "refresh_2min": "2 分钟",
            "refresh_5min": "5 分钟",
            "refresh_15min": "15 分钟",
            "refresh_30min": "30 分钟",
            "refresh_adaptive": "自适应",
            "Quit": "退出",
            "language_title": "语言",
            "language_system": "跟随系统",
            "check_provider_status_title": "检查提供商状态",
            "status_operational": "正常运行",
            "status_degraded": "性能下降",
            "status_partial_outage": "部分中断",
            "status_major_outage": "重大中断",
            "status_maintenance": "维护中",
            "status_unknown": "状态未知",
            "Status Page": "状态页",
        ],
        "zh-Hant": [
            "Historical tracking": "歷史追蹤",
            "Show reset time as clock": "以時鐘時間顯示重置時間",
            "Show usage as used": "以已用量顯示",
            "quota_depleted_title": "配額用完與恢復",
            "threshold_warnings_title": "門檻提醒",
            "predictive_pace_warnings_title": "預測性節奏提醒",
            "quota_warning_sound": "播放通知音效",
            "show_credits_extra_usage_title": "顯示額度 + 額外使用量",
            "hide_personal_info_title": "隱藏個人資訊",
            "refresh_on_open_title": "開啟選單時重新整理",
            "Refresh": "重新整理",
            "refresh_interval_title": "重新整理間隔",
            "refresh_manual": "手動",
            "refresh_1min": "1 分鐘",
            "refresh_2min": "2 分鐘",
            "refresh_5min": "5 分鐘",
            "refresh_15min": "15 分鐘",
            "refresh_30min": "30 分鐘",
            "refresh_adaptive": "自適應",
            "Quit": "結束",
            "language_title": "語言",
            "language_system": "依照系統",
            "check_provider_status_title": "檢查提供者狀態",
            "status_operational": "運作正常",
            "status_degraded": "效能下降",
            "status_partial_outage": "部分服務中斷",
            "status_major_outage": "重大服務中斷",
            "status_maintenance": "維護中",
            "status_unknown": "狀態未知",
            "Status Page": "狀態頁",
        ],
    ]
}
#endif
